apiVersion: v1
kind: ConfigMap
metadata:
  name: db-env
data:
  DB_NAME: "khoatranrvc_db"
  DB_USER: "khoatranrvc"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: a2hvYXRyYW5ydmMxMjM=